# Transformers Practical Questions (21–30)



In [1]:
!pip install transformers sentence-transformers torch

## Question 21

In [2]:
from transformers import GPT2Tokenizer

# Load GPT-2 tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
text = "Large Language Models are transforming the world."
# Tokenize text
tokens = tokenizer.tokenize(text)
# Convert tokens to IDs
token_ids = tokenizer.convert_tokens_to_ids(tokens)
# Print results
print("Tokens:", tokens)
print("Token IDs:", token_ids)


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Tokens: ['Large', 'ĠLanguage', 'ĠModels', 'Ġare', 'Ġtransforming', 'Ġthe', 'Ġworld', '.']
Token IDs: [21968, 15417, 32329, 389, 25449, 262, 995, 13]


## Question 22

In [3]:
from transformers import AutoTokenizer

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("gpt2")

# Compare two words
for word in ["unbelievable","cat"]:
    # Tokenize each word
    tokens = tokenizer.tokenize(word)
    print(word,"->",tokens)

# Explanation:
# Rare/complex words are split into subword tokens.
# Common words like "cat" usually remain a single token.


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

unbelievable -> ['un', 'bel', 'iev', 'able']
cat -> ['cat']


## Question 23

In [4]:
from transformers import pipeline

# Load text-generation pipeline
generator = pipeline("text-generation", model="gpt2")

# Prompt
prompt = "Artificial Intelligence is"
# Generate twice
out1 = generator(prompt,max_new_tokens=50)
out2 = generator(prompt,max_new_tokens=50)
print(out1[0]["generated_text"])
print("-"*50)
print(out2[0]["generated_text"])

# Outputs may differ because sampling is random by default.


model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
[transformers] Both `max_new_tokens` (=50) and `max_length

Artificial Intelligence is not always as good as it seems.

A computer is probably best trained to recognize when an AI is near it, rather than when it is close.

I've been doing research on these ideas in the past, and I have the
--------------------------------------------------
Artificial Intelligence is a very promising area to explore for many years as it could be used to create new jobs and create new technologies, such as artificial intelligence.

The world's biggest AI company, AIB Inc., is already working on a prototype AI that will


## Question 24

In [5]:
from transformers import AutoTokenizer

tokenizer=AutoTokenizer.from_pretrained("bert-base-uncased")

sentences=[
"Hello world",
"Transformers are powerful models",
"AI"
]

# Pad to equal length
encoded=tokenizer(sentences,padding=True,return_tensors="pt")

print(encoded["input_ids"])
print(encoded["attention_mask"])


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tensor([[  101,  7592,  2088,   102,     0,     0],
        [  101, 19081,  2024,  3928,  4275,   102],
        [  101,  9932,   102,     0,     0,     0]])
tensor([[1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 0, 0, 0]])


## Question 25

In [6]:
import torch
from transformers import AutoTokenizer, AutoModel
from torch.nn.functional import cosine_similarity

# Load BERT tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

# Sentences with different meanings of "bank"
sents = [
    "I deposited money in the bank.",
    "The fisherman sat near the bank of the river."
]

# Store embeddings
embeds = []

# Extract the embedding for the word "bank"
for s in sents:
    inputs = tokenizer(s, return_tensors="pt")
    outputs = model(**inputs)
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    idx = tokens.index("bank")
    embeds.append(outputs.last_hidden_state[0, idx])

# Compare the two embeddings
print("Cosine similarity:", cosine_similarity(embeds[0], embeds[1], dim=0))

# Lower similarity shows that BERT creates context-aware embeddings.

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Cosine similarity: tensor(0.5026, grad_fn=<SumBackward1>)


## Question 26

In [7]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model=SentenceTransformer("all-MiniLM-L6-v2")

sentences=[
"Artificial Intelligence",
"Machine Learning",
"I love pizza"
]

emb=model.encode(sentences)
sim=cosine_similarity(emb)

print(sim)

# AI and Machine Learning should have higher similarity than Pizza.


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

[[1.0000004  0.7034628  0.12694836]
 [0.7034628  1.0000002  0.08875052]
 [0.12694836 0.08875052 1.0000001 ]]


## Question 27

In [8]:
import torch
import math

# Create a random input matrix
X = torch.rand(3, 4)
# Use the input as Query, Key, and Value
Q = K = V = X
# Compute scaled dot-product attention scores
scores = (Q @ K.T) / math.sqrt(Q.shape[-1])
# Apply softmax to get attention weights
weights = torch.softmax(scores, dim=-1)
# Compute the context vectors
context = weights @ V
print(weights)
print(context)


tensor([[0.3221, 0.3428, 0.3351],
        [0.2915, 0.3575, 0.3510],
        [0.2882, 0.3550, 0.3568]])
tensor([[0.4753, 0.0786, 0.2903, 0.3112],
        [0.4907, 0.0791, 0.2899, 0.3180],
        [0.4929, 0.0789, 0.2894, 0.3184]])


## Question 28

In [9]:
import torch

# Define input dimensions
batch = 2
seq = 5
embed_dim = 32
heads = 4
head_dim = embed_dim // heads

# Create a random input tensor
X = torch.rand(batch, seq, embed_dim)

# Split input into multiple attention heads
Q = X.view(batch, seq, heads, head_dim).transpose(1, 2)
K = Q
V = Q

# Compute attention scores
scores = torch.matmul(Q, K.transpose(-2, -1)) / head_dim**0.5

# Apply softmax to get attention weights
weights = torch.softmax(scores, dim=-1)

# Compute context vectors
context = torch.matmul(weights, V)

# Concatenate all attention heads
concat = context.transpose(1, 2).contiguous().view(batch, seq, embed_dim)

# Apply the final linear projection
linear = torch.nn.Linear(embed_dim, embed_dim)
output = linear(concat)

# Print output shapes
print("Concatenated:", concat.shape)
print("Projected:", output.shape)

Concatenated: torch.Size([2, 5, 32])
Projected: torch.Size([2, 5, 32])


## Question 29

In [10]:
import torch

# Create a random attention score matrix
scores = torch.rand(5, 5)
# Create a causal (look-ahead) mask
mask = torch.triu(torch.ones(5, 5), diagonal=1).bool()
# Replace masked values with -infinity
masked = scores.masked_fill(mask, float("-inf"))
# Apply softmax to get attention weights
soft = torch.softmax(masked, dim=-1)
# Print original scores
print(scores)
print(masked)
print(soft)


tensor([[0.5075, 0.8149, 0.8267, 0.9712, 0.7056],
        [0.7200, 0.7152, 0.4519, 0.2861, 0.3052],
        [0.2797, 0.5829, 0.0421, 0.8899, 0.8068],
        [0.7832, 0.1396, 0.7977, 0.3473, 0.8025],
        [0.1355, 0.1064, 0.5356, 0.4158, 0.3575]])
tensor([[0.5075,   -inf,   -inf,   -inf,   -inf],
        [0.7200, 0.7152,   -inf,   -inf,   -inf],
        [0.2797, 0.5829, 0.0421,   -inf,   -inf],
        [0.7832, 0.1396, 0.7977, 0.3473,   -inf],
        [0.1355, 0.1064, 0.5356, 0.4158, 0.3575]])
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5012, 0.4988, 0.0000, 0.0000, 0.0000],
        [0.3182, 0.4309, 0.2509, 0.0000, 0.0000],
        [0.3138, 0.1649, 0.3184, 0.2029, 0.0000],
        [0.1657, 0.1609, 0.2472, 0.2193, 0.2069]])


## Question 30

In [11]:

import torch
import torch.nn as nn
# Define a GPT-style Decoder Block
class DecoderBlock(nn.Module):

    # Constructor to initialize the layers
    def __init__(self, d_model=32, heads=4):
        super().__init__()

        # Create a Multi-Head Self-Attention layer
        # d_model = embedding dimension
        # heads = number of attention heads
        # batch_first=True expects input as (batch_size, sequence_length, embedding_dimension)
        self.attn = nn.MultiheadAttention(d_model, heads, batch_first=True)

        # Layer Normalization after the attention block
        self.norm1 = nn.LayerNorm(d_model)

        # Feed Forward Neural Network
        self.ff = nn.Sequential(

            # First fully connected layer (32 → 64)
            nn.Linear(d_model, 64),

            # Apply ReLU activation function
            nn.ReLU(),

            # Second fully connected layer (64 → 32)
            nn.Linear(64, d_model)
        )

        # Layer Normalization after the Feed Forward Network
        self.norm2 = nn.LayerNorm(d_model)

    # Forward pass of the decoder block
    def forward(self, x):

        # Get the sequence length from the input tensor
        seq = x.size(1)
        # Create an upper triangular mask for causal (look-ahead) attention
        mask = torch.triu(torch.ones(seq, seq), 1).bool()
        # Apply masked multi-head self-attention
        attn, _ = self.attn(x, x, x, attn_mask=mask)
        # Add residual connection and apply Layer Normalization
        x = self.norm1(x + attn)
        # Pass the result through the Feed Forward Network
        ff = self.ff(x)
        # Add another residual connection and apply Layer Normalization
        x = self.norm2(x + ff)
        return x
model = DecoderBlock()

# Generate a random input tensor
# Shape = (batch_size=2, sequence_length=5, embedding_dimension=32)
inp = torch.rand(2, 5, 32)
# Pass the input through the decoder block
out = model(inp)
print("Input Shape :", inp.shape)
print("Output Shape:", out.shape)


Input Shape : torch.Size([2, 5, 32])
Output Shape: torch.Size([2, 5, 32])
